# Generated by Django 5.1.1 on 2024-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='feedback_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
